name: Build Android APK
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Install App Dependencies
        run: |
          cd ShareMobileApp
          npm install

      - name: Install Server Dependencies
        run: |
          cd ShareMobileApp/nodejs-assets/nodejs-project
          npm install

      - name: Build APK (Debug Mode with Extra Memory)
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
        run: |
          cd ShareMobileApp/android
          chmod +x gradlew
          ./gradlew assembleDebug --no-daemon --stacktrace --console=plain

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Share-AboElnazer-APK
          path: ShareMobileApp/android/app/build/outputs/apk/debug/app-debug.apk